name: Static checks
on:
  pull_request: {}
  push:
    branches:
    - master
jobs:
  markdown_lint:
    name: Markdown lint
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout code
      # actions/checkout@v2
      uses: actions/checkout@722adc6
    - name: Markdown lint
      run: bin/markdownlint-all